fineract:
  enabled: true
  db: fineract-mysql
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: "openmf/fineract:latest"
  spec:
    template:
       spec:
         containers:
            env:
              FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "default"
              FINERACT_DEFAULT_TENANTDB_NAME: "fineract_default"
              FINERACT_DEFAULT_TENANTDB_HOSTNAME: "mysql.infra.svc.cluster.local"
              FINERACT_DEFAULT_TENANTDB_PORT: "3306"
              FINERACT_HIKARI_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
              FINERACT_HIKARI_JDBC_URL: jdbc:mariadb://mysql.infra.svc.cluster.local:3306/fineract_tenants
              FINERACT_SERVER_PORT: 8443
  preStopScript: 'echo -e "******Fineract is stopping********";'
  ingress:
    enabled: true
    hostname: "2-fynams.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "*.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "1m"
      memory: "100m"

communityapp:
  enabled: true
  lookforservice: true
  image: "openmf/community-app:latest"
  ingress:
    enabled: true
    hostname: "2-communityapp.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "2-communityapp.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "500m"

webapp:
  enabled: false
  image: "fintecheando/web-app:master"
  ingress:
    enabled: true
    hostname: "2-webapp.sandbox.fynarfin.io"
    path: "/web"
    annotations:
      kubernetes.io/ingress.class: "nginx"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "500m"

selfservice:
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/fineract/phee-ns/web-self-service-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/self"
    annotations: {}


mariadb:
  enabled: false


mysql:
  fullnameOverride: fineract-mysql
  enabled: false
  image:
    tag: "10.5.16-debian-11-r22"
    debug: true
  auth:
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      # create databases
      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
      CREATE DATABASE IF NOT EXISTS `fineract_default`;
      # create root user and grant rights
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
  primary:
    resources:
      requests:
        memory: "500m"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

wildcardhostname: "*.sandbox.fynarfin.io"

tls: ""